# fly.toml app configuration file generated for erisa-mongodb-test on 2024-06-07T00:01:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# app = "erisa-mongodb-test"
app = 'msc-mongodb'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

swap_size_mb = 1024

[experimental]
  auto_rollback = true
  cmd = ["mongod", "--ipv6"]

[build]
  image = 'mongo:4.2.23'

[env]
  MONGO_INITDB_DATABASE = 'modmail'
  # MONGO_INITDB_ROOT_PASSWORD = 'secret'
  MONGO_INITDB_ROOT_USERNAME = 'root'

[[mounts]]
  source = 'mongo_data'
  destination = '/data/db'
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
